### ISSUE TITLE
Issue with > 1.3.x In Web Client

### ISSUE THREAD

**Issue by chrisadubois** [webex/ts-sdp#13]
Currently - the webex-js-sdk plugin-meetings imports ^1.0.1 of this package. It ends up resolving actually 1.0.1 but for other downstream apps, like the web client, it will pull the 1.3.x version (due to the caret, I believe). 

After doing a yarn upgrade to berry in the web client, I noticed that there was an issue with codec.fmtParams.map, because fmtParams is *actually* already a map.

This could be a cluster of dependencies and babel, but regardless, forcing a resolution to 1.0.1 within the web client resolved issues, so I'm opening this ticket for the purposes of visibility that the most recent version of this package may not actually be working as intended within the web-client usage.

Feel free to ping me on webex and we can discuss deeper.

**Comment by bbaldino** [comment]
Will handle this by fixing the version spec on the web client side...but technically maybe we should've done a breaking change in ts-sdp for the fmtParams change.
